GET http://localhost:8080
Accept: text/plain

###


GET http://localhost:8080
Accept: text/event-stream

###

GET http://localhost:8080
Accept: application/stream+json

###

GET http://localhost:8080/stream
Accept: application/json

###

GET http://localhost:8080/stream
Accept: text/event-stream

###

GET http://localhost:8080/stream
Accept: application/stream+json

###

GET http://localhost:8080/stream2
Accept: application/stream+json

###

POST http://localhost:8080/echo
Content-Type: application/json

"aaa"
###

POST http://localhost:8080/stream
Accept: text/event-stream
Content-Type: application/stream+json

{"value":1}
{"value":2}
{"value":3}
###

GET http://localhost:8080/handler
Accept: application/json

###

GET http://localhost:8080/handler/stream
Accept: application/json

###

POST http://localhost:8080/handler/echo
Accept: application/json

"aaa"
###

POST http://localhost:8080/handler/stream

{"value":1}
{"value":2}
{"value":3}
###